### ISSUE TITLE
Issue with typescript-vim

### ISSUE THREAD

**Issue by blacksails** [Quramy/vim-js-pretty-template#1]
Hi 

I hoped to be able to use this together with typescript vim unfortunately I get something weird.
![screen shot 2016-04-28 at 09 58 54](https://cloud.githubusercontent.com/assets/3807831/14879214/385930ee-0d28-11e6-9999-e91bdf71c654.png)

This might be an issue with typescript-vim i am not really sure.

**Comment by blacksails** [comment]
In some places it works just fine
![screen shot 2016-04-28 at 10 09 53](https://cloud.githubusercontent.com/assets/3807831/14879409/6c949fc8-0d29-11e6-9514-2169c3b0c084.png)

It has something to do with closing braces `}`

**Comment by Quramy** [comment]
Hi @blacksails .

Please try this:

```vim
autocmd FileType typescript syn clear foldBraces
```

**Comment by blacksails** [comment]
@Quramy you are a god.

**Comment by blacksails** [comment]
But there is still one issue, for some reason i cannot get it to automatically highligt whenever I open a ts file.

**Comment by blacksails** [comment]
Nevermind. It works perfectly 👍  Nice plugin btw.

**Comment by Quramy** [comment]
Thanks for your reporting :)  I'll append the setting to README.md for typescript users.
