### ISSUE TITLE
Breaks on tagged template strings

### ISSUE THREAD

**Issue by shannonmoeller** [Quramy/vim-js-pretty-template#2]
Works like a charm on plain template strings, but breaks when a tag is used.

``` js
import { html } from './template-helpers';

const foo = `<div>This works.</div>`;
const bar = html`<div class="baz">This doesn't.</div>`;
```

Not breaking on a tagged string would be nice. Formatting based on the tag would be superb; just like GitHub's highlighting above.

**Comment by vasco3** [comment]
@shannonmoeller did you find a working alternative?

**Comment by nicksrandall** [comment]
I've looked at the code but I can't see why it doesn't work. I'd love to contribute if somebody could point me in the right direction.

**Comment by shannonmoeller** [comment]
Just noticed you added this. Thanks!
